[View in Colaboratory](https://colab.research.google.com/github/nmehra98/mlfrstassgn/blob/master/Assignment_16.ipynb)

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.preprocessing import*
%matplotlib inline

In [53]:
# Question 1

from sklearn.datasets import load_wine

wine=load_wine()
x=wine.data
y=wine.target

x.shape,y.shape

((178, 13), (178,))

In [0]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [43]:
# Question 2 A

model = DecisionTreeClassifier()
num_trees = 100
model1 = BaggingClassifier(base_estimator=model)
model1

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [45]:
model1.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [46]:
pred = model1.predict(x_test)
pred

array([0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 2, 2, 1, 0, 2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0, 2,
       2, 0, 1, 2, 0, 1, 2, 2, 0, 0])

In [47]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9814814814814815

In [48]:
from sklearn.metrics import classification_report

print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        21
          1       1.00      0.94      0.97        18
          2       0.94      1.00      0.97        15

avg / total       0.98      0.98      0.98        54



In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[21,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 15]])

In [0]:
# Question 2 B

from sklearn.ensemble import RandomForestClassifier

In [58]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [59]:
pred1 = rf.predict(x_test)
pred1

array([0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 2, 2, 1, 0, 2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0, 2,
       2, 0, 1, 2, 0, 1, 2, 2, 0, 0])

In [60]:
metrics.accuracy_score(y_test,pred1)

0.9814814814814815

In [61]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        21
          1       1.00      0.94      0.97        18
          2       0.94      1.00      0.97        15

avg / total       0.98      0.98      0.98        54



In [62]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred1)

array([[21,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 15]])

In [0]:
# Question 2 C

from sklearn.ensemble import GradientBoostingClassifier


In [65]:
model2 = GradientBoostingClassifier()
model2

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [66]:
model2.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [67]:
pred2 = model2.predict(x_test)
pred2

array([0, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 2, 2, 1, 0, 2, 0, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0, 2,
       2, 0, 1, 2, 0, 1, 2, 2, 0, 0])

In [68]:
metrics.accuracy_score(y_test,pred2)

0.9259259259259259

In [69]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       0.95      0.90      0.93        21
          1       0.89      0.89      0.89        18
          2       0.94      1.00      0.97        15

avg / total       0.93      0.93      0.93        54



In [70]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred2)

array([[19,  2,  0],
       [ 1, 16,  1],
       [ 0,  0, 15]])

In [0]:
# Question 2 D

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [0]:
list = []
h1 = LogisticRegression()
h2 = DecisionTreeClassifier()
h3 = svm.SVC()

In [88]:
list = VotingClassifier([('LogisticRegression', h1), ('DecisionTreeClassifier', h2), ('SVM', h3)])
list

VotingClassifier(estimators=[('LogisticRegression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [89]:
list.fit(x_train,y_train)

VotingClassifier(estimators=[('LogisticRegression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [90]:
pred3 = list.predict(x_test)
pred3

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 2, 2, 1, 0, 2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0, 2,
       2, 0, 1, 1, 0, 1, 2, 2, 0, 0])

In [91]:
metrics.accuracy_score(y_test,pred3)

0.9629629629629629

In [92]:
print(classification_report(y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        21
          1       0.94      0.94      0.94        18
          2       0.93      0.93      0.93        15

avg / total       0.96      0.96      0.96        54



In [93]:
confusion_matrix(y_test,pred3)

array([[21,  0,  0],
       [ 0, 17,  1],
       [ 0,  1, 14]])