[View in Colaboratory](https://colab.research.google.com/github/nmehra98/mlfrstassgn/blob/master/Assignment_12.ipynb)

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.preprocessing import*
%matplotlib inline

In [0]:
#Question 1

# P(Yes|Sunny)= (P(Sunny|Yes)P(Yes))/P(Sunny)

# P(Sunny|Yes) = 1/3
# P(Yes) = 9/14
# P(Sunny) = 5/14

# P(Yes|Sunny) = 3/5

In [0]:
#Question 2

# A

from sklearn.datasets import load_iris

In [0]:
i=load_iris()
x=i.data
y=i.target

In [5]:
x.shape,y.shape

((150, 4), (150,))

In [0]:
# B

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [0]:
# C


from sklearn.naive_bayes import GaussianNB

In [11]:
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB(priors=None)

In [12]:
pred = model.predict(x_test)
pred

array([0, 0, 0, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 2, 2, 2, 2, 0, 2, 0, 1, 0, 0, 1, 1, 0, 1, 2, 1,
       0])

In [0]:
# C 1

from sklearn.metrics import confusion_matrix

In [14]:
confusion_matrix(y_test,pred)

array([[16,  0,  0],
       [ 0, 15,  1],
       [ 0,  0, 13]])

In [15]:
# C 2

from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.94      0.97        16
          2       0.93      1.00      0.96        13

avg / total       0.98      0.98      0.98        45



In [17]:
# D

from sklearn.naive_bayes import MultinomialNB

model1=MultinomialNB()
model1.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [19]:

pred1  =  model1.predict(x_test)
pred1

array([0, 0, 0, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 0, 0, 0,
       0, 1, 2, 0, 0, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 1,
       0])

In [20]:
# D 1

confusion_matrix(y_test,pred1)

array([[16,  0,  0],
       [ 0, 10,  6],
       [ 0,  0, 13]])

In [21]:
# D 2

print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.62      0.77        16
          2       0.68      1.00      0.81        13

avg / total       0.91      0.87      0.86        45

