[View in Colaboratory](https://colab.research.google.com/github/nmehra98/mlfrstassgn/blob/master/Assignment_15.ipynb)

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.preprocessing import*
%matplotlib inline

In [72]:
from sklearn.datasets import load_digits

digit=load_digits()
x=digit.data
y=digit.target

x.shape,y.shape

((1797, 64), (1797,))

In [73]:
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler().fit_transform(x)
x_std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [74]:
from sklearn.decomposition import PCA
pca = PCA(n_components=8)
pca.fit(x_std)

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [75]:
principalComponents = pca.fit_transform(x_std)
principalComponents

array([[ 1.91419746, -0.95439493, -3.94545883, ...,  0.53219638,
        -1.39557791,  1.5245371 ],
       [ 0.58911142,  0.92446515,  3.92510582, ..., -0.67742529,
         1.85259209,  0.575744  ],
       [ 1.30198498, -0.3169048 ,  3.02358374, ...,  0.91792774,
        -1.23240477,  1.05099063],
       ...,
       [ 1.02241551, -0.14786343,  2.46965444, ..., -0.00735429,
         0.36623593,  0.51640022],
       [ 1.07564526, -0.38052785, -2.45725794, ..., -0.62744036,
         1.02096798,  0.72310536],
       [-1.25806945, -2.22795109,  0.28191887, ...,  2.34143404,
        -0.44650992, -1.20066306]])

In [76]:
principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2','principal component 3','principal component 4','principal component 5','principal component 6','principal component 7','principal component 8'])
principalDf

# new x

principal component 1  principal component 2  principal component 3  \
0                  1.914197              -0.954395              -3.945459   
1                  0.589111               0.924465               3.925106   
2                  1.301985              -0.316905               3.023584   
3                 -3.020440              -0.868864              -0.800488   
4                  4.529037              -1.093716               0.973255   
5                 -1.301766              -1.148350              -1.573850   
6                  1.434454              -2.957742               2.832195   
7                  0.614296               5.462316               0.657648   
8                 -1.098820              -0.665474              -0.042331   
9                 -0.538329              -0.776759              -1.569755   
10                 3.378834              -0.495984              -2.280766   
11                 2.063045               2.017327               1.539375   
12                -1.936943              -1.815035               2.802348   
13                -3.257998               2.149427              -1.614757   
14                 5.458393               0.025188               0.180649   
15                -3.877115               2.606451               1.858192   
16                 0.921600              -3.262417               3.402129   
17                 1.415264               1.954571               0.560838   
18                -0.926618               2.253109               1.532974   
19                -2.370574              -2.932731              -0.380450   
20                 2.001863              -1.319206              -2.570967   
21                 1.694641               2.075951               0.885056   
22                -3.114486              -1.058634               2.452005   
23                -1.469212               3.910748              -2.076462   
24                 4.002999              -0.321573               0.586108   
25                -0.376844               0.525815               1.356443   
26                 1.286832              -3.969087               2.543229   
27                 3.842150               3.477978              -1.570756   
28                -0.166905               0.934599               1.258399   
29                -2.014297              -2.377214              -0.708056   
...                     ...                    ...                    ...   
1767               4.958378              -1.159726               0.643773   
1768               1.009211              -3.326159              -0.584273   
1769              -0.542868              -0.493596              -3.139699   
1770              -3.314725               1.510941              -0.820226   
1771               2.128317              -2.821821               3.623885   
1772              -1.814403               1.198199              -3.115094   
1773               1.374671              -4.417765               0.544411   
1774               0.762730               0.643630               3.117914   
1775              -0.433320               3.215558               2.008144   
1776              -0.525923              -1.155085              -1.890888   
1777               5.106538              -0.289168               0.340357   
1778               5.900815              -1.709996               1.861016   
1779               1.597131               4.676130               0.469193   
1780              -5.137972              -0.190393               2.224621   
1781              -1.416281              -1.032026               1.194435   
1782              -4.272791              -1.355338               3.061782   
1783              -3.136535              -1.411457               2.240947   
1784               1.568528              -0.438999              -1.841537   
1785               0.058040               1.977801               1.804800   
1786              -0.711309               0.253214              -2.934024   
17

In [82]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444412, 0.06498403, 0.04859049,
       0.04214054, 0.03938651, 0.03385327])

In [0]:
from sklearn.model_selection import train_test_split
principalDf_train,principalDf_test,y_train,y_test=train_test_split(principalDf,y,test_size=0.3)

In [79]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()
reg.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [0]:
pred = reg.predict(principalDf_test)

In [86]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.8592592592592593

In [87]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.94      0.93      0.93        54
          1       0.75      0.84      0.80        51
          2       0.88      0.90      0.89        50
          3       0.83      0.83      0.83        54
          4       0.95      0.91      0.93        65
          5       0.86      0.98      0.92        52
          6       0.94      0.94      0.94        54
          7       0.89      0.98      0.93        55
          8       0.86      0.54      0.66        56
          9       0.67      0.73      0.70        49

avg / total       0.86      0.86      0.86       540



In [88]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[50,  0,  0,  0,  2,  0,  2,  0,  0,  0],
       [ 0, 43,  3,  0,  0,  0,  1,  0,  0,  4],
       [ 0,  2, 45,  1,  0,  0,  0,  2,  0,  0],
       [ 1,  0,  0, 45,  0,  1,  0,  0,  1,  6],
       [ 1,  2,  0,  0, 59,  1,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 51,  0,  0,  1,  0],
       [ 1,  1,  0,  0,  1,  0, 51,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 54,  1,  0],
       [ 0,  7,  3,  2,  0,  4,  0,  2, 30,  8],
       [ 0,  2,  0,  6,  0,  2,  0,  1,  2, 36]])